import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <header className="w-full py-6 flex justify-center items-center">
          <img src="/vigovia.png" alt="Vigovia Logo" className="h-16" />
        </header>
        {children}

        <footer className="w-full border-t mt-10 py-8">
          <div className="w-auto mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 px-50 text-center md:text-left">
            <div>
              <div className="font-bold text-lg mb-2">Vigovia Tech Pvt. Ltd</div>
              <div className="text-sm text-gray-600">
                Registered Office: Hd-109 Cinnabar Hills,<br />
                Links Business Park, Karnataka, India.
              </div>
            </div>
            <div>
              <div className="font-bold text-lg mb-2">Contact</div>
              <div className="text-sm text-gray-600">Phone: +91-9999999999</div>
              <div className="text-sm text-gray-600">Email ID: Contact@Vigovia.Com</div>
            </div>
            <div className="flex flex-col items-center">
              <img src="/vigovia.png" alt="Vigovia Logo" className="h-16" />
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
