import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: { padding: 24, fontFamily: 'Helvetica', fontSize: 12, backgroundColor: '#fff' },
  header: { flexDirection: 'column', alignItems: 'center', marginBottom: 16, borderBottom: '2px solid #e0e0e0', paddingBottom: 8 },
  logo: { height: 40, marginBottom: 4 },
  titleBox: { backgroundColor: '#7b6cf6', color: '#fff', borderRadius: 12, padding: 12, marginBottom: 12, width: '100%', textAlign: 'center' },
  infoContainer: { border: '1px solid #e0e0e0', borderRadius: 8, padding: 10, marginBottom: 12 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 2 },
  infoCell: { flex: 1, textAlign: 'center' },
  dayContainer: { flexDirection: 'row', marginVertical: 12, alignItems: 'flex-start' },
  dayLabel: { backgroundColor: '#5b4dc2', borderRadius: 12, minWidth: 36, minHeight: 120, justifyContent: 'center', alignItems: 'center', marginRight: 12, padding: 4 },
  dayLabelText: { color: 'white', fontWeight: 'bold', fontSize: 12, textAlign: 'center', transform: 'rotate(-90deg)' },
  dayContent: { flex: 1, flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  imageContainer: { alignItems: 'center', marginRight: 12 },
  imagePlaceholder: { width: 80, height: 80, borderRadius: 40, overflow: 'hidden', border: '2px solid #e0e0e0', marginBottom: 4, backgroundColor: '#eee', justifyContent: 'center', alignItems: 'center' },
  timelineContainer: { alignItems: 'center', marginRight: 8, marginTop: 8 },
  timelineItem: { alignItems: 'center' },
  timelineDot: { alignItems: 'center', marginVertical: 4 },
  timelineLine: { width: 2, height: 20, backgroundColor: '#7b6cf6' },
  activityRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, minHeight: 28 },
  activityTime: { fontWeight: 'bold', minWidth: 70, marginRight: 8 },
  sectionTitle: { fontWeight: 'bold', fontSize: 16, color: 'black', marginBottom: 8 },
  sectionTitleAccent: { color: '#7b6cf6' },
  borderedContainer: { border: '1px solid #7b6cf6', borderRadius: 8, marginBottom: 8, flexDirection: 'row', alignItems: 'center', padding: 8 },
  tableContainer: { borderRadius: 8, backgroundColor: '#f7f3ff', overflow: 'hidden', marginBottom: 8 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#3d2966', borderTopLeftRadius: 8, borderTopRightRadius: 8 },
  tableHeaderCell: { color: 'white', fontWeight: 'bold', textAlign: 'center', padding: 6, fontSize: 11 },
  tableRow: { flexDirection: 'row', backgroundColor: '#f7f3ff' },
  tableCell: { textAlign: 'center', padding: 6, fontSize: 10 },
  noteText: { fontSize: 9, color: '#555', marginTop: 8 },
  footer: { borderTop: '1px solid #e0e0e0', paddingTop: 8, flexDirection: 'row', justifyContent: 'space-between', fontSize: 10, color: 'black', width: '90%', margin: 'auto' },
  footerSection: { flex: 1, textAlign: 'left' },
  footerTitle: { fontWeight: 'bold', fontSize: 12 },
  footerText: { fontSize: 10 },
  footerLogo: { height: 32, marginBottom: 2, alignSelf: 'center' },
  planPackGoText: { fontSize: 24, fontWeight: 'bold', color: '#3d2966', marginBottom: 16, textAlign: 'center' },
  bookNowButton: { backgroundColor: '#3d2966', borderRadius: 8, paddingHorizontal: 32, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  bookNowText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
});
